language: rust
matrix:
  include:
    - rust: 1.20.0
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
script:
  - cargo test
  - cargo test --no-default-features
